---
title: ""
---

## Upcoming events

Date and time    |      Speakers     |   Title   |  Venue | 
----------- | ------------ | ---------------------- | ---------- | ---------
<b> May 18th, 5.30pm </b>  | [Ella Kaye](http://www2.warwick.ac.uk/fac/sci/statistics/staff/research_students/kaye/) and Tim Lucas, University of Oxford | **Ranking items scalably with the Bradley-Terry model: An introduction to the BradleyTerryScalable package**, and <br> **Caret and zoon: machine learning, ecology and domain specific package systems.** | [Larkin Room, St John's College](https://www.sjc.ox.ac.uk/documents/55/SJC-Map-Apr2015web.pdf.download.pdf) | [Sign up form](https://goo.gl/forms/hUvrGzHmeqpIka3j2)
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;


## Past events

Date and time    |      Speakers     |   Title   |  Venue | 
----------- | ------------ | ---------------------- | ---------- | ---------
<b> April 5th, 5.30pm </b>  | [Martin John Hadley](https://twitter.com/martinjhnhadley) and [Kaspar Märtens](https://twitter.com/kasparmartens), University of Oxford | **Interactive graphics with Shiny & R**, and <br> **R Markdown and R Notebooks** | [Larkin Room, St John's College](https://www.sjc.ox.ac.uk/documents/55/SJC-Map-Apr2015web.pdf.download.pdf) | [Sign up form](https://goo.gl/forms/8V6gJeE21ELiBteA2)
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;

**Interactive graphics with Shiny & R**

R is well known as a powerful tool for data analysis (or even "data science") but fewer users are aware of how R can be used for publishing beautiful interactive charts, maps and network diagrams using htmlwidget libraries. Further, through the use of the Shiny library, it's possible to create responsive, interactive web applications that provide exploratory interfaces for research datasets.
This talk introduces the basics of these technologies and how the Interactive Data Network (http://www.idn.it.ox.ac.uk) in IT Services provides support and hosting for shiny web apps that expose Open Access datasets.

**R Markdown and R Notebooks**

R Markdown documents provide a convenient way to create automatic reports and make your analysis fully reproducible. Recently, R Notebooks have been introduced, allowing code chunks to be executed independently and interactively. This short talk will cover the basics of R Notebooks and compare these to the standard R Markdown documents. 


Date and time    |      Speakers     |   Title   |  Venue
----------- | ------------ | ---------------------- | ----------
<b> November 10th, 6pm </b>  | [Louis Aslett](http://www.louisaslett.com), University of Oxford | **Cheap and cheerful massively parallel batch R processing on EC2**  | St John's College
&nbsp; | &nbsp; | &nbsp; | &nbsp;

**Cheap and cheerful massively parallel batch R processing on EC2**

The Amazon EC2 service provides a scalable computing resource enabling clusters of compute power to be provisioned and destroyed quickly making it an economical option when large compute resources are only needed in bursts.  In particular, a feature called spot instances can make using EC2 extremely inexpensive, although at the expense unpredictably delayed launch and/or early termination of your instances.

This talk will first give a brief background to EC2 and spot instances for anyone who is unfamiliar with them, and then preview some forthcoming changes to the Amazon EC2 RStudio AMIs maintained by Louis Aslett (http://www.louisaslett.com/RStudio_AMI/).  These changes are geared toward making it easy to leverage the cheapest spot instances to process large quantities of R batch jobs in parallel, with robustness to delayed launch and early termination of such instances, enabling cost savings of up to 90%.

